package main

import (
	"bytes"
	"cmp"
	"context"
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"maps"
	"net/http"
	"net/url"
	"slices"
	"strconv"
	"strings"
)

// verify runs under ctx, which the hub owns; the request is already answered.
func (h *Hub) verify(ctx context.Context, sub subscription) {
	defer h.tasks.Done()
	want, sep := rand.Text(), "?"
	if strings.Contains(sub.callback, "?") {
		sep = "&" // the callback's own query is kept verbatim, overlapping names included
	}
	sub.expiresAt = h.now().Add(lease)
	got, err := h.exchange(ctx, http.MethodGet, sub.callback+sep+url.Values{
		"hub.mode": {"subscribe"}, "hub.topic": {topic},
		"hub.challenge": {want}, "hub.lease_seconds": {strconv.Itoa(int(lease.Seconds()))},
	}.Encode(), nil, "", len(want)+1)
	if err == nil && string(got) != want {
		err = fmt.Errorf("challenge mismatch: got %d bytes, want %d", len(got), len(want))
	}

	supersededBy := h.finishVerification(sub, err == nil)
	switch {
	case err != nil:
		h.log.Warn("verification failed", "subscription", sub.revision, "failure", err)
	case supersededBy != 0:
		h.log.Info("verified but superseded", "subscription", sub.revision, "by", supersededBy)
	default:
		h.log.Info("verified", "subscription", sub.revision)
	}
}

// handlePublish delivers within the request's lifetime: caller cancellation,
// the broadcast budget, or a forced shutdown (which closes the connection)
// stops attempts not yet started and cancels the one in progress.
func (h *Hub) handlePublish(w http.ResponseWriter, r *http.Request) {
	ctx, cancel := context.WithTimeout(r.Context(), h.budget)
	defer cancel()
	sum := summary{EventID: rand.Text()}
	body, err := json.Marshal(event{sum.EventID, h.now().UTC(), "Generated by the WebSub demonstration hub"})
	if err != nil {
		http.Error(w, "could not generate payload", http.StatusInternalServerError)
		return
	}

	// Recipients are fixed at the start, oldest subscription first so the
	// order does not depend on map iteration.
	h.mu.Lock()
	cbs := slices.DeleteFunc(slices.Collect(maps.Keys(h.subs)), func(cb string) bool { return !h.live(h.subs[cb]) })
	slices.SortFunc(cbs, func(a, b string) int { return cmp.Compare(h.subs[a].revision, h.subs[b].revision) })
	h.mu.Unlock()

	sum.Selected = len(cbs)
	for _, cb := range cbs {
		// Re-read so a renewal committed during the broadcast is signed with
		// its new secret; one can still commit just after this read.
		h.mu.Lock()
		sub, ok := h.subs[cb]
		h.mu.Unlock()
		if ctx.Err() != nil {
			sum.NotAttempted++
		} else if !ok || !h.live(sub) {
			sum.SkippedExpired++
		} else if _, err := h.exchange(ctx, http.MethodPost, cb, body, sub.secret, 0); err != nil {
			sum.Attempted, sum.Failed = sum.Attempted+1, sum.Failed+1
			h.log.Warn("delivery failed", "event", sum.EventID, "subscription", sub.revision, "failure", err)
		} else {
			sum.Attempted, sum.Acknowledged = sum.Attempted+1, sum.Acknowledged+1
		}
	}
	h.log.Info("published", "event", sum.EventID, "selected", sum.Selected, "acknowledged", sum.Acknowledged,
		"failed", sum.Failed, "skipped_expired", sum.SkippedExpired, "not_attempted", sum.NotAttempted)
	w.Header().Set("Content-Type", "application/json")
	if err := json.NewEncoder(w).Encode(sum); err != nil {
		h.log.Warn("publish summary not written", "event", sum.EventID, "err", err)
	}
}

// exchange makes one bounded callback request, signing body when a secret is
// given, and returns up to limit bytes of a 2xx response. Its errors omit the
// callback URL, whose query may carry credentials.
func (h *Hub) exchange(ctx context.Context, method, target string, body []byte, secret string, limit int) ([]byte, error) {
	ctx, cancel := context.WithTimeout(ctx, h.timeout)
	defer cancel()
	req, err := http.NewRequestWithContext(ctx, method, target, bytes.NewReader(body))
	if err != nil {
		return nil, errors.New("invalid callback")
	}
	if secret != "" {
		mac := hmac.New(sha256.New, []byte(secret))
		mac.Write(body)
		req.Header.Set("Content-Type", "application/json")
		req.Header.Set("X-Hub-Signature", "sha256="+hex.EncodeToString(mac.Sum(nil)))
	}
	resp, err := h.client.Do(req)
	switch {
	case errors.Is(err, context.DeadlineExceeded):
		return nil, errors.New("timeout")
	case errors.Is(err, context.Canceled):
		return nil, errors.New("canceled")
	case err != nil:
		return nil, errors.New("transport failure")
	}
	defer resp.Body.Close()
	if resp.StatusCode/100 != 2 {
		return nil, fmt.Errorf("unexpected status %d", resp.StatusCode)
	}
	got, err := io.ReadAll(io.LimitReader(resp.Body, int64(limit)))
	if err != nil {
		return nil, errors.New("response read failed")
	}
	return got, nil
}
