package main

import (
	"errors"
	"log/slog"
	"net/http"
	"sync"
	"time"
)

const (
	topic        = "a-topic"
	formType     = "application/x-www-form-urlencoded"
	maxForm      = 16 << 10 // bytes in a subscription request body
	eventMessage = "Generated by the WebSub demonstration hub"
)

// limits bound the hub's outbound work and storage.
type limits struct {
	exchangeTimeout time.Duration // one callback request
	broadcastBudget time.Duration // one whole publish
	maxVerifying    int
	maxPublishing   int
	maxCallbacks    int // distinct callbacks, stored or being verified
}

var defaultLimits = limits{
	exchangeTimeout: 5 * time.Second,
	broadcastBudget: 8 * time.Second,
	maxVerifying:    16,
	maxPublishing:   4,
	maxCallbacks:    1000,
}

type subscription struct {
	callback  string
	secret    string
	expiresAt time.Time
	revision  uint64
}

type event struct {
	EventID     string    `json:"event_id"`
	GeneratedAt time.Time `json:"generated_at"`
	Message     string    `json:"message"`
}

// summary counts the recipients of one broadcast:
// selected = attempted + skipped_expired + not_attempted, and
// attempted = acknowledged + failed.
type summary struct {
	EventID        string `json:"event_id"`
	Selected       int    `json:"selected"`
	Attempted      int    `json:"attempted"`
	Acknowledged   int    `json:"acknowledged"`
	Failed         int    `json:"failed"`
	SkippedExpired int    `json:"skipped_expired"`
	NotAttempted   int    `json:"not_attempted"`
}

type outcome int

const (
	acknowledged outcome = iota
	failed
	skippedExpired
	notAttempted
)

func (s *summary) add(o outcome) {
	s.Selected++
	switch o {
	case acknowledged:
		s.Attempted++
		s.Acknowledged++
	case failed:
		s.Attempted++
		s.Failed++
	case skippedExpired:
		s.SkippedExpired++
	case notAttempted:
		s.NotAttempted++
	}
}

func (s summary) logAttrs() []any {
	return []any{
		"event", s.EventID, "selected", s.Selected, "acknowledged", s.Acknowledged,
		"failed", s.Failed, "skipped_expired", s.SkippedExpired, "not_attempted", s.NotAttempted,
	}
}

// Hub holds the subscriptions and tracks the verifications it has admitted.
// The fields after mu are guarded by it.
type Hub struct {
	limits
	mux    http.Handler
	client *http.Client
	log    *slog.Logger
	now    func() time.Time
	tasks  sync.WaitGroup // admitted verifications

	mu            sync.Mutex
	closed        bool
	lastRevision  uint64
	verifications int            // in progress
	verifying     map[string]int // in progress, per callback
	publishing    int
	broadcasts    uint64 // started so far; rotates where the next one starts
	subs          map[string]subscription
}

var errShuttingDown = errors.New("hub is shutting down")

func (h *Hub) isLive(s subscription) bool { return h.now().Before(s.expiresAt) }

func (h *Hub) releasePublish() {
	h.mu.Lock()
	defer h.mu.Unlock()
	h.publishing--
}
